config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars, except: [:update] do 
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cars, through: :bookings
  has_many :cars
  has_many :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def index
    @bookings = Booking.all
    # raise
  end
  
  def create 
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @car = Car.find(params[:car_id])
    @booking.car = @car  
    @booking.save
    redirect_to bookings_path
    # raise
  end

  def destroy 
    @booking = Booking.find(params[:id])
    @car = @booking.car
    @booking.destroy
    # raise
    redirect_to bookings_path
  end

  private 

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index 
    @cars = Car.all
  end

  def new 
    @car = Car.new
  end

  def show 
    @car = Car.find(params[:id])
    @booking = Booking.new
  end 

  def create 
    @car = Car.new(car_params)
    @car.user = current_user
    @car.save
    redirect_to cars_path
  end

  def update 
    # @car = Car.find(params[:id])
    # @car.update(car_params)
    # redirect_to car_path(@car)
  end

  def destroy 
    @car = Car.find(params[:id])
    @car.destroy
    # raise
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :id)
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@car, @booking] do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.submit "Book", class: "btn btn-primary" %>
<% end %>

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>
  <%#= link_to car_path(booking.car_id) do %>
  <div>
    <%= booking.car.make %>
    <%= booking.car.model %>
     <%= link_to "Delete this booking", booking_path(booking) , :method => :delete, data: {:confirm => "Are you sure you want to remove this booking?"} %>
  </div>  
  <%# end %>
<% end %>
  

app/views/cars/index.html.erb
<% @cars.each do |car| %>
  <%= link_to car_path(car) do %>
    <%= car.make %>
    <%= car.model %>
  <% end %>
<% end %>

<%= link_to "Add Car", new_car_path, class:"btn btn-primary" %>
<%= link_to "Bookings", bookings_path, class:"btn btn-danger" %>

app/views/cars/new.html.erb
<%= simple_form_for(@car) do |f| %>
  <%= f.label :make %>
  <%= f.text_field :make %>
  <%= f.label :model %>
  <%= f.text_field :model %>
  <%= f.submit %>
<% end %>

app/views/cars/show.html.erb
<%= @car.make %>
<%= @car.model %>


<p>Book this <%= @car.make %> now</p>
<%= render 'bookings/form' %>

<%= link_to "Cars Index", cars_path  %>

   <%= link_to "Delete this car", car_path(@car) , :method => :delete, data: {:confirm => "Are you sure you want to remove this booking?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="page-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<section class="hero-container">
  <div class="color-body">
    <h1 class="page-title h1 font-weight-bold">
      Premium Car Rental in <span class="underline">London</span>
    </h1>
    <p class="font-weight-light page-extract mt-64">
      Don’t deny yourself the pleasure of driving the most exotic cars from around the world.
    </p>
  </div>
  <%= image_tag "porsche1.png", class: 'hero-img' %>
</section>

<section class="hero-search mt-128 w-100">
  <div class="home-search">
    <%= form_tag cars_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Pick-up date"
      %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Return date"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</section>

<section class="container-right">
  <div class="color-body">
    <h2 class="page-title h1 font-weight-bold">
      Key Features
    </h2>
    <p class="font-weight-light page-extract mt-16">
      We are all about cars, thats why we provide a first class service
    </p>
  </div>
</section>

<section class="home-feature-section">
  <div class="home-card-container mt-64">
    <div class="home-card">
    </div>
    <div class="home-card">
    </div>
    <div class="home-card">
    </div>
    <div class="home-card">
    </div>
  </div>

</section>






<%= link_to "All Cars", cars_path, class: "btn btn-primary" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <h1>cars.</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "cars", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>